version: "3.9"
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foosball
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: foosball
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
